name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install `Angular CLI gh-pages`
        run: npm install angular-cli-ghpages --save-dev

      - name: Build
        run: |
          npm install
          ng build --prod --base-href "https://lucaslar.github.io/vis-lg-heur/"
      
      - name: Deploy
        run: npx angular-cli-ghpages --dir=dist/vis-lg-heur
